title: "Yogha Pradana | Embedded Systems & AI"  
description: "Building intelligent systems at the hardware-software frontier."  
url: "https://yoghapradana.github.io"  
theme: jekyll-theme-cayman  # Ensure the theme is spelled correctly  
plugins:  
  - jekyll-feed  
  - jekyll-seo-tag  
